### ISSUE TITLE
Lowercase statuses

### ISSUE THREAD

**Issue by ilyakaznacheev** [dhalenok/pyheroku-badge#1]
I think it would be more usual to write statuses in lowercase instead of a capital case:
`Deployed` -> `deployed`
because many other badges do so, and Heroku badge looks like a poor brother:
![](https://habrastorage.org/webt/c_/sp/y1/c_spy1jkx1jetno6b2qprgrba9u.png)

**Comment by dhalenok** [comment]
Resolved by 3109ad55f3b8abf0cbe3d71742b112e31e156a6c.
